### ISSUE TITLE
Add Newsletter Link

### ISSUE THREAD

**Issue by Alexandershel** [strykeforce/strykeforce.org#84]
We need to add the link for newsletter sign up to the top of the blog page. If we could say, "Sign up for our monthly newsletter!" Can we have the link set up as hypertext on the words "monthly newsletter"? Thank you!

http://eepurl.com/bBlRN1

**Comment by jhh** [comment]
Preview of changes are up: https://deploy-preview-85--strykeforce.netlify.com

Let me know if you are OK with it or would like any changes.

**Comment by Alexandershel** [comment]
Perfect! Thank you so much.
