### ISSUE TITLE
Calendar Update

### ISSUE THREAD

**Issue by Alexandershel** [strykeforce/strykeforce.org#88]
Delete events that happened before the October 17th.

Add NRG event:

[[events]]
name = "NRG Competition"
date = 2019-20-19T00:00:00Z
venue = "Portage District Library"
street = "300 Library Ln"
city = "Portage"
state = "MI"
zip = "49002"

**Comment by jhh** [comment]
Thx for the new event.

I've been keeping past events on the list to show what we did for the season. I'm fine either way but maybe we can discuss briefly tonight at the shop. Maybe link to the TBA results page for past events?

**Comment by jhh** [comment]
It looks like the date is wrong in the snippet posted above. If you're in tonight maybe we can walk through how you do a pull request for this and how our publishing works.
